name: SCA Scan on merge to main
on:
  push:
    branches: [main, DATAGO-142436-fossa-guardian-onboarding]

permissions:
  contents: read
  id-token: write
  packages: read
  actions: read
  statuses: write
  checks: write
  pull-requests: write

jobs:
  sca_scan:
    uses: SolaceDev/solace-public-workflows/.github/workflows/sca-scan-and-guard.yaml@main
    with:
      use_vault: true
      config_file: '.github/workflow-config.json'

  update_manifest:
    needs: sca_scan
    # if: needs.sca_scan.result == 'success' && github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
      - name: Update solace-cloud-manifest dev entry (sha + version)
        uses: SolaceDev/maas-build-actions/.github/actions/update-dynamodb-release-manifest@master
        with:
          release_tag: dev
          squad: launch-pad
          repository: ${{ github.event.repository.name }}
          version: ${{ github.ref_name }}
          sha: ${{ github.sha }}
